import { useMemo, useState } from 'react'
import { Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, CalendarClock, CheckCircle2, ChevronDown, CircleHelp, ClipboardList, Compass, FileText, Filter, Heart, MapPin, Menu, Search, ShieldCheck, Sparkles, Users, Wrench, X } from 'lucide-react'
import { jobs, projects, services } from './data'
import { isBackendConfigured, supabase } from './lib/supabase'
import type { Job, Project, Service } from './types'

const categories = [
 { name:'Home Cleaning', icon:'🧹', count:'Daily & deep clean' }, { name:'Electrician', icon:'⚡', count:'Repairs & installation' },
 { name:'Plumber', icon:'🔧', count:'Leaks & fittings' }, { name:'AC Repair', icon:'❄️', count:'Service & installation' },
 { name:'Computer Repair', icon:'💻', count:'Laptop, PC & CCTV' }, { name:'Tutors', icon:'📚', count:'Learn from experts' },
 { name:'Beauty & Wellness', icon:'✨', count:'At-home appointments' }, { name:'Carpenter', icon:'🪚', count:'Furniture & fittings' }
]
type Notice = { title:string; body:string }
function App() {
 const [mobileOpen, setMobileOpen] = useState(false)
 const [notice, setNotice] = useState<Notice | null>(null)
 const [saved, setSaved] = useState<string[]>([])
 const showNotice = (title:string, body:string) => setNotice({title,body})
 const toggleSaved = (id:string) => setSaved(old => old.includes(id) ? old.filter(x=>x!==id) : [...old,id])
 return <div className="app-shell">
  <header className="topbar"><div className="nav-wrap">
   <Link to="/" className="brand" aria-label="BharatConnect home"><span className="brand-mark">B</span><span>Bharat<span className="brand-green">Connect</span><small>LOCAL • WORK • GROW</small></span></Link>
   <button className="mobile-toggle icon-btn" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen?<X/>:<Menu/>}</button>
   <nav className={mobileOpen?'nav-links open':'nav-links'}>
    <NavLink to="/services" onClick={()=>setMobileOpen(false)}>Find Services</NavLink><NavLink to="/jobs" onClick={()=>setMobileOpen(false)}>Find Jobs</NavLink><NavLink to="/freelance" onClick={()=>setMobileOpen(false)}>Freelance</NavLink><NavLink to="/business" onClick={()=>setMobileOpen(false)}>For Business</NavLink>
   </nav>
   <div className="nav-actions"><button className="btn btn-quiet" onClick={()=>showNotice('Sign in','Authentication will be enabled after you connect and configure the hosted Supabase project. No fake account is created.')}>Log in</button><button className="btn btn-primary" onClick={()=>showNotice('Join BharatConnect','Choose a role after backend authentication is configured. Registration is not active in demo mode.')}>Get started <ArrowRight size={16}/></button></div>
  </div></header>
  <Routes>
   <Route path="/" element={<Home onNotice={showNotice} onSave={toggleSaved} saved={saved}/>}/>
   <Route path="/services" element={<ServicesPage onNotice={showNotice} onSave={toggleSaved} saved={saved}/>}/>
   <Route path="/jobs" element={<JobsPage onNotice={showNotice} onSave={toggleSaved} saved={saved}/>}/>
   <Route path="/freelance" element={<FreelancePage onNotice={showNotice}/>}/>
   <Route path="/business" element={<BusinessPage onNotice={showNotice}/>}/>
   <Route path="/dashboard" element={<Dashboard onNotice={showNotice} saved={saved}/>}/>
   <Route path="*" element={<NotFound/>}/>
  </Routes>
  <Footer/>
  {notice && <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setNotice(null)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-btn" onClick={()=>setNotice(null)} aria-label="Close"><X/></button><div className="modal-icon"><Sparkles/></div><h2 id="modal-title">{notice.title}</h2><p>{notice.body}</p><button className="btn btn-primary full-btn" onClick={()=>setNotice(null)}>Got it</button></section></div>}
 </div>
}

function SearchPanel({initial='', onSearch}:{initial?:string;onSearch:(q:string,loc:string)=>void}) {
 const [q,setQ]=useState(initial), [loc,setLoc]=useState('')
 return <form className="search-panel" onSubmit={e=>{e.preventDefault();onSearch(q,loc)}}><label className="search-field"><Search size={20}/><span className="sr-only">Search</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Service, job title, skill or company"/></label><label className="location-field"><MapPin size={19}/><span className="sr-only">City or PIN code</span><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="City or PIN code"/></label><button className="btn btn-primary search-submit" type="submit">Search <ArrowRight size={17}/></button></form>
}
function Home({onNotice,onSave,saved}:{onNotice:(t:string,b:string)=>void;onSave:(id:string)=>void;saved:string[]}) {
 const navigate=useNavigate()
 return <main><section className="hero"><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> YOUR CITY. MORE OPPORTUNITIES.</div><h1>Good work.<br/><span>Right nearby.</span></h1><p className="hero-sub">Book trusted local services, find your next job, or grow your freelance career — all in one place.</p><SearchPanel onSearch={(q,loc)=>navigate(`/services?q=${encodeURIComponent(q)}&loc=${encodeURIComponent(loc)}`)}/><div className="hero-trust"><span><ShieldCheck size={17}/> Trust-focused profiles</span><span><CheckCircle2 size={17}/> Free job applications</span></div><div className="hero-stats"><div><strong>Local first</strong><span>Find people nearby</span></div><div><strong>Work for all</strong><span>Jobs & projects</span></div><div><strong>Free to start</strong><span>No job application fees</span></div></div></div><div className="hero-visual"><div className="visual-glow"/><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-illustration"><div className="ill-top"><span className="live-dot"/> NEAR YOU <span className="ill-menu">•••</span></div><div className="ill-map"><div className="map-line line-a"/><div className="map-line line-b"/><div className="map-line line-c"/><span className="map-pin pin-a">⚡</span><span className="map-pin pin-b">🔧</span><span className="map-pin pin-c">💻</span><span className="map-home">⌂</span></div><div className="ill-bottom"><div className="avatar-stack"><i>R</i><i>S</i><i>A</i></div><div><b>Skilled people, closer</b><small>Discover services around you</small></div><span className="ill-check"><CheckCircle2/></span></div></div><div className="float-card float-card-jobs"><div className="float-icon"><BriefcaseBusiness/></div><div><b>New opportunities</b><small>Jobs that fit your skills</small></div><span className="float-dot"/></div><div className="float-card float-card-trust"><div className="float-icon green"><BadgeCheck/></div><div><b>Trust, built in</b><small>Clear profile signals</small></div></div></div></div></section>
 <section className="section category-section"><div className="section-heading"><div><span className="kicker">WHAT DO YOU NEED?</span><h2>Find help for everyday life</h2><p>Explore popular services from local professionals.</p></div><Link className="text-link" to="/services">All services <ArrowRight size={17}/></Link></div><div className="category-grid">{categories.map(c=><button key={c.name} className="category-card" onClick={()=>navigate(`/services?q=${encodeURIComponent(c.name)}`)}><span className="category-emoji">{c.icon}</span><strong>{c.name}</strong><small>{c.count}</small><ArrowRight className="category-arrow" size={16}/></button>)}</div></section>
 <section className="section services-highlight"><div className="section-heading"><div><span className="kicker">LOCAL PROFESSIONALS</span><h2>Good people. Great work.</h2><p>Explore sample provider profiles. Listings are illustrative until connected to a live backend.</p></div><Link className="text-link" to="/services">Browse providers <ArrowRight size={17}/></Link></div><div className="service-grid">{services.slice(0,3).map(s=><ServiceCard key={s.id} service={s} onNotice={onNotice} onSave={onSave} saved={saved.includes(s.id)}/>)}</div></section>
 <section className="section opportunity-band"><div><span className="kicker light">YOUR NEXT CHAPTER STARTS HERE</span><h2>Looking for work?<br/>Make your next move.</h2><p>Explore roles, find clients, and let your skills do the talking.</p><div className="band-actions"><Link to="/jobs" className="btn btn-lime">Explore jobs <ArrowRight size={17}/></Link><Link to="/freelance" className="btn btn-outline-light">Find projects</Link></div></div><div className="band-graphic"><div className="band-circle circle-a"/><div className="band-circle circle-b"/><div className="band-paper"><div className="paper-check"><CheckCircle2/></div><b>YOUR NEXT OPPORTUNITY</b><span/><span/><span className="short-line"/><div className="paper-pill">Ready to grow ↗</div></div><div className="band-star">✳</div></div></section>
 <section className="section how-section"><div className="section-heading centered"><div><span className="kicker">SIMPLE BY DESIGN</span><h2>Three steps. New possibilities.</h2><p>Built to make local discovery and work opportunities easier.</p></div></div><div className="steps-grid"><Step number="01" icon={<Compass/>} title="Discover" text="Search by skill, service, location or PIN code."/><Step number="02" icon={<Users/>} title="Connect" text="Review profiles and send a booking, application or proposal request."/><Step number="03" icon={<ShieldCheck/>} title="Move forward" text="Track your activity and build trust through clear, honest profiles."/></div></section>
 <section className="section cta-strip"><div className="cta-icon"><Building2/></div><div><h3>Are you a local professional or employer?</h3><p>Build your presence and reach people looking for what you offer.</p></div><Link to="/business" className="btn btn-primary">Grow with us <ArrowRight size={17}/></Link></section>
 </main>
}
function Step({number,icon,title,text}:{number:string;icon:React.ReactNode;title:string;text:string}) {return <div className="step-card"><div className="step-top"><span>{number}</span><div className="step-icon">{icon}</div></div><h3>{title}</h3><p>{text}</p></div>}
function ServiceCard({service,onNotice,onSave,saved}:{service:Service;onNotice:(t:string,b:string)=>void;onSave:()=>void;saved:boolean}) {
 return <article className="service-card"><div className="service-card-top"><div className="provider-avatar">{service.initials}</div><button className={saved?'save-btn saved':'save-btn'} aria-label={saved?'Unsave provider':'Save provider'} onClick={onSave}><Heart size={18} fill={saved?'currentColor':'none'}/></button></div><div className="provider-name-row"><h3>{service.title}</h3>{service.verified&&<BadgeCheck size={17} className="verified-icon"/>}</div><div className="provider-meta"><span>{service.category}</span><span>★ {service.rating}</span></div><p>{service.description}</p><div className="provider-location"><MapPin size={15}/>{service.location}</div><div className="service-card-bottom"><strong>{service.price}</strong><button className="btn btn-small btn-primary" onClick={()=>onNotice('Request a booking',`Booking requests for ${service.title} will be enabled when the secure backend is connected. No request has been sent.`)}>Request <ArrowRight size={14}/></button></div></article>
}
function ServicesPage({onNotice,onSave,saved}:{onNotice:(t:string,b:string)=>void;onSave:(id:string)=>void;saved:string[]}) {
 const params=new URLSearchParams(window.location.search)
 const [q,setQ]=useState(params.get('q')||''),[loc,setLoc]=useState(params.get('loc')||''),[cat,setCat]=useState('All services')
 const filtered=useMemo(()=>services.filter(s=>(!q||`${s.title} ${s.category} ${s.description}`.toLowerCase().includes(q.toLowerCase()))&&(!loc||s.location.toLowerCase().includes(loc.toLowerCase()))&&(cat==='All services'||s.category===cat)),[q,loc,cat])
 return <main className="listing-page"><div className="page-banner"><div className="page-banner-inner"><span className="kicker light">LOCAL SERVICES</span><h1>Find the right help,<br/><span>right around you.</span></h1><p>Discover service professionals for home, work and everyday needs.</p><SearchPanel initial={q} onSearch={(a,b)=>{setQ(a);setLoc(b)}}/></div></div><div className="section"><div className="listing-toolbar"><div><h2>Local professionals</h2><p>{filtered.length} illustrative profiles · Browse free</p></div><label className="filter-select"><Filter size={16}/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All services</option>{[...new Set(services.map(s=>s.category))].map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></label></div>{filtered.length?<div className="service-grid">{filtered.map(s=><ServiceCard key={s.id} service={s} onNotice={onNotice} onSave={()=>onSave(s.id)} saved={saved.includes(s.id)}/>)}</div>:<Empty title="No matching providers yet" text="Try a broader service name or a nearby city."/>}</div></main>
}
function JobsPage({onNotice,onSave,saved}:{onNotice:(t:string,b:string)=>void;onSave:(id:string)=>void;saved:string[]}) {
 const [q,setQ]=useState(''),[loc,setLoc]=useState(''),[type,setType]=useState('All types')
 const filtered=useMemo(()=>jobs.filter(j=>(!q||`${j.title} ${j.company} ${j.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase()))&&(!loc||j.location.toLowerCase().includes(loc.toLowerCase()))&&(type==='All types'||j.type===type)),[q,loc,type])
 return <main className="listing-page"><div className="page-banner jobs-banner"><div className="page-banner-inner"><span className="kicker light">CAREER OPPORTUNITIES</span><h1>Your skills deserve<br/><span>a great next step.</span></h1><p>Explore opportunities from local and remote employers. Applying should always be free.</p><SearchPanel initial={q} onSearch={(a,b)=>{setQ(a);setLoc(b)}}/></div></div><section className="section"><div className="listing-toolbar"><div><h2>Explore jobs</h2><p>{filtered.length} illustrative listings · Never pay to apply</p></div><label className="filter-select"><Filter size={16}/><select value={type} onChange={e=>setType(e.target.value)}><option>All types</option>{['Full-time','Part-time','Contract','Remote'].map(t=><option key={t}>{t}</option>)}</select><ChevronDown size={15}/></label></div><div className="jobs-layout"><div className="job-list">{filtered.map(j=><JobCard key={j.id} job={j} saved={saved.includes(j.id)} onSave={()=>onSave(j.id)} onNotice={onNotice}/>)}</div><aside className="jobs-aside"><div className="aside-icon"><FileText/></div><h3>Make your next move count</h3><p>Keep your profile up to date and prepare a clear, honest resume.</p><button className="btn btn-primary full-btn" onClick={()=>onNotice('Resume profile','Resume uploads and applications need secure authentication and private storage. Configure the backend before uploading personal documents.')}>Create a profile <ArrowRight size={16}/></button><small>Free to browse and apply. Always.</small></aside></div></section></main>
}
function JobCard({job,saved,onSave,onNotice}:{job:Job;saved:boolean;onSave:()=>void;onNotice:(t:string,b:string)=>void}) {
 return <article className="job-card"><div className="company-avatar">{job.company.split(' ').map(w=>w[0]).slice(0,2).join('')}</div><div className="job-main"><div className="job-title-row"><h3>{job.title}</h3><button className={saved?'save-btn saved':'save-btn'} onClick={onSave} aria-label={saved?'Unsave job':'Save job'}><Heart size={18} fill={saved?'currentColor':'none'}/></button></div><strong className="company-name">{job.company}</strong><div className="job-meta"><span><MapPin size={14}/>{job.location}</span><span><BriefcaseBusiness size={14}/>{job.type}</span><span><CalendarClock size={14}/>{job.posted}</span></div><div className="job-tags">{job.tags.map(t=><span key={t}>{t}</span>)}</div></div><div className="job-apply"><strong>{job.salary}</strong><button className="btn btn-small btn-primary" onClick={()=>onNotice('Apply for free',`This is a sample listing for ${job.title}. Live applications will be enabled after employer data, authentication and application permissions are configured. Applying will remain free.`)}>Apply free <ArrowRight size={14}/></button></div></article>
}
function FreelancePage({onNotice}:{onNotice:(t:string,b:string)=>void}) {
 const [q,setQ]=useState(''),[cat,setCat]=useState('All categories')
 const filtered=projects.filter(p=>(!q||`${p.title} ${p.description} ${p.category}`.toLowerCase().includes(q.toLowerCase()))&&(cat==='All categories'||p.category===cat))
 return <main className="listing-page"><div className="page-banner freelance-banner"><div className="page-banner-inner"><span className="kicker light">FREELANCE & PROJECTS</span><h1>Great work starts<br/><span>with a connection.</span></h1><p>Find projects that fit your skills, or bring your next idea to life.</p><form className="search-panel compact-search" onSubmit={e=>e.preventDefault()}><label className="search-field"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects or skills"/></label><button className="btn btn-primary search-submit" type="submit">Search <ArrowRight size={17}/></button></form></div></div><section className="section"><div className="listing-toolbar"><div><h2>Open project briefs</h2><p>{filtered.length} illustrative projects</p></div><label className="filter-select"><Filter size={16}/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All categories</option>{[...new Set(projects.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></label></div><div className="project-grid">{filtered.map(p=><ProjectCard key={p.id} project={p} onNotice={onNotice}/>)}</div><div className="info-callout"><ShieldCheck/><div><b>Fair work, clear terms.</b><p>Agree on scope, milestones and delivery before starting. This starter does not include payments or escrow.</p></div></div></section></main>
}
function ProjectCard({project,onNotice}:{project:Project;onNotice:(t:string,b:string)=>void}) {return <article className="project-card"><div className="project-card-top"><span className="project-category">{project.category}</span><span className="project-symbol"><ClipboardList/></span></div><h3>{project.title}</h3><p>{project.description}</p><div className="project-client"><Building2 size={15}/>{project.client}</div><div className="project-facts"><div><small>Budget range</small><strong>{project.budget}</strong></div><div><small>Timeline</small><strong>{project.timeline}</strong></div></div><button className="btn btn-primary full-btn" onClick={()=>onNotice('Send a proposal',`Proposal submission for “${project.title}” requires a live account and secure backend. No proposal has been sent.`)}>View brief & propose <ArrowRight size={16}/></button></article>}
function BusinessPage({onNotice}:{onNotice:(t:string,b:string)=>void}) {return <main className="business-page"><section className="business-hero"><span className="kicker light">FOR LOCAL BUSINESSES & EMPLOYERS</span><h1>More visibility.<br/><span>Better connections.</span></h1><p>Reach nearby customers, find talent and build your professional presence — with free basics and optional promotions.</p><div className="business-actions"><button className="btn btn-lime" onClick={()=>onNotice('Create a business profile','Business profiles require verified accounts and backend storage. Connect Supabase and configure role policies before enabling registration.')}>Create free profile <ArrowRight size={17}/></button><button className="btn btn-outline-light" onClick={()=>onNotice('Promoted listings','Optional promotions can be added later with transparent pricing and clearly labelled sponsored placements.')}>Explore promotions</button></div><div className="business-benefits"><span><CheckCircle2/> Free to get started</span><span><CheckCircle2/> Local discovery</span><span><CheckCircle2/> Optional promotions</span></div></section><section className="section business-features"><div className="section-heading centered"><div><span className="kicker">BUILT FOR GROWTH</span><h2>Everything starts with a profile</h2><p>Simple tools for service providers, employers and independent professionals.</p></div></div><div className="feature-grid"><Feature icon={<Wrench/>} title="Service providers" text="Show your skills, service areas, indicative pricing and portfolio."/><Feature icon={<BriefcaseBusiness/>} title="Employers" text="Publish clear job descriptions and manage applicants in one place."/><Feature icon={<Users/>} title="Freelancers" text="Present your work, discover briefs and submit proposals."/><Feature icon={<ShieldCheck/>} title="Trust & transparency" text="Verification states and reviews should be earned and auditable."/></div></section></main>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) {return <article className="feature-card"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function Dashboard({onNotice,saved}:{onNotice:(t:string,b:string)=>void;saved:string[]}) {return <main className="section dashboard-page"><span className="kicker">YOUR SPACE</span><h1>Dashboard</h1><p>Saved items on this device: {saved.length}. This starter stores saved IDs only in the current session.</p><div className="dashboard-grid"><Feature icon={<Heart/>} title="Saved items" text={`${saved.length} items saved in this session.`}/><Feature icon={<ClipboardList/>} title="Bookings & applications" text="Live activity appears after backend setup."/><Feature icon={<ShieldCheck/>} title="Account & verification" text="Identity and business checks are not active in demo mode."/></div><button className="btn btn-primary" onClick={()=>onNotice('Backend status',isBackendConfigured&&supabase?'Supabase credentials are present. Confirm database migrations, authentication settings and row-level security policies before production use.':'No backend configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY as GitHub Actions variables, then configure Supabase RLS and auth.')}>Check setup <ArrowRight size={16}/></button></main>}
function Empty({title,text}:{title:string;text:string}) {return <div className="empty-state"><Search size={28}/><h3>{title}</h3><p>{text}</p></div>}
function NotFound() {return <main className="section not-found"><CircleHelp size={42}/><h1>Page not found</h1><p>The page may have moved.</p><Link className="btn btn-primary" to="/">Back home</Link></main>}
function Footer() {return <footer className="footer"><div className="footer-main"><div className="footer-brand"><Link to="/" className="brand"><span className="brand-mark">B</span><span>Bharat<span className="brand-green">Connect</span><small>LOCAL • WORK • GROW</small></span></Link><p>Helping India find local services and better work opportunities.</p><div className="footer-status"><span className="status-dot"/>{isBackendConfigured?'Backend credentials detected · verify policies':'Preview mode · backend not configured'}</div></div><div className="footer-links"><div><b>Discover</b><Link to="/services">Local services</Link><Link to="/jobs">Find jobs</Link><Link to="/freelance">Freelance projects</Link></div><div><b>For business</b><Link to="/business">Business profiles</Link><Link to="/business">Employer tools</Link><Link to="/dashboard">Dashboard</Link></div><div><b>Trust & safety</b><a href="#privacy" onClick={e=>{e.preventDefault();alert('Publish a reviewed privacy policy before launch.')}}>Privacy principles</a><a href="#safety" onClick={e=>{e.preventDefault();alert('Reporting and moderation workflows require backend setup.')}}>Safety & reporting</a><a href="#help" onClick={e=>{e.preventDefault();alert('Add a support contact before public launch.')}}>Help centre</a></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} BharatConnect. Built for local opportunity.</span><span>Job applications should always be free.</span></div></footer>}
export default App
